app/urls.py
from django.urls import path, include

from . import views
app_name = 'app'
urlpatterns = [
	path('', views.index, name='index'),
	path('list-events', views.list_events, name='list-events'),
	path('process-clock-event', views.process_clock_event,
		name='process_clock_event'),
]

clockinout/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views

urlpatterns = [
	path('app/', include('app.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

app/models.py
from django.db import models
from django.forms import ModelForm

class User(models.Model):
	''' An abstract base class to represent a user.
	Attributes:
	 - first_name -- A string to represent this User's first name.
	 - last_name -- A string to represent this User's last name. 
	'''
	first_name = models.CharField(max_length=100)
	last_name = models.CharField(max_length=100)
	
	def __str__(self):
		return self.first_name + " " + self.last_name
		
	class Meta:
		abstract = True

class Teacher(User):
	''' A class to represent a teacher. Inherits from abstract User.
	Attributes:
	 - name -- A string to represent this Teacher's name.
	'''
	pass
	
	
class Clock(models.Model):
	''' A class to represent a clock-event by a Teacher.
	Attributes:
	- date_time -- The date and time of the clock-event.
	- type -- Two-option string field for whether the Teacher clocked in or out. 
	- user -- The Teacher who clocked in or out.
	'''
	TYPE_CHOICES = (
		('IN', 'Clock-In'),
		('OUT', 'Clock-Out')
	)
	date_time = models.DateTimeField('Clock-event time', auto_now_add=True)
	type = models.CharField(max_length=3, choices=TYPE_CHOICES)
	user = models.ForeignKey(Teacher, on_delete=models.CASCADE)
	
	def __str__(self):
		return str(self.user) + " Clocked-" + self.type + " on " + str(self.date_time)
		
class ClockForm(ModelForm):
	'''A Form class for clocking in or out with a Clock event. '''
	class Meta:
		model = Clock
		fields = ('user', 'type')

app/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404
from .models import Clock, ClockForm

def index(request):
	context = {}
	context['clock_form'] = ClockForm()
	return render(request, 'app/index.html', context)

def list_events(request):
	clock_events = Clock.objects.order_by('-date_time')
	context = { 'event_list': clock_events }
	return render(request, 'app/list-events.html', context)
	
def process_clock_event(request):
	if request.method == "POST":
		data = request.POST
		teacher = data["user"]
		type = data["type"]
		form = ClockForm(data=data)
		if form.is_valid():
			clock_event = form.save()
		else:
			raise Http404("Invalid form submission. Please try again.")
	return HttpResponseRedirect('/app')

app/templates/app/index.html
<h2> Hi! <h2/>
<h3> Please clock-in or clock-out below. </h3>

<form action="{% url 'app:process_clock_event' %}" method="post">
{% csrf_token %}
{{ clock_form.as_p }}
<input type="submit" value="Submit!" name="clock">
</form>

<h3> Want to see all clock events? </h3>
<a href="{% url 'login' %}"> Click here. </a>

app/templates/app/list-events.html
{% if user.is_authenticated %}
{% if event_list %}
	<h3> Here is a list of all clock events </h3>
	<ul>
	{% for event in event_list %}
		<li> {{ event }} </li>
	{% endfor %}
	</ul>
{% else %}
	<p> No one has clocked in or out yet :(. </p>
{% endif %}
{% else %}
	<h3> Only administrators can view clock events </h3>
{% endif %}